language: python

sudo: false

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env:
      - TOX_ENV=py27-dj18
      - TOX_ENV=py27-dj19
      - TOX_ENV=py27-dj110
    - python: 3.3
      env:
      - TOX_ENV=py33-dj18
    - python: 3.4
      env:
      - TOX_ENV=py34-dj18
      - TOX_ENV=py34-dj19
      - TOX_ENV=py34-dj110
    - python: 3.5
      env:
      - TOX_ENV=py35-dj18
      - TOX_ENV=py35-dj19
      - TOX_ENV=py35-dj110

install:
  - travis_retry pip install "virtualenv<14.0.0" "tox>=1.9" "coverage<4"

script:
  - tox -e $TOX_ENV

after_success:
  - pip install codecov
  - codecov -e TOX_ENV
