language: python

sudo: false

env:
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35

matrix:
  fast_finish: true
  include:
    - python: 3.5
      env:
      - TOX_ENV=py35

install:
  - travis_retry pip install "virtualenv<14.0.0" "tox>=1.9" "coverage<4"

script:
  - tox -e $TOX_ENV

after_success:
  - pip install codecov
  - codecov -e TOX_ENV
